#!/bin/bash
Str=`grep -i background_opacity ~/.config/alacritty/alacritty.yml`
Str=${Str:20:5}

num=$(awk "BEGIN {print $Str+0.05; exit}")

echo $num #debug

if (( $(echo "$num > 1" |bc -l) )); then
	num=1.0 
fi

sed -i "/background_opacity:.*/c\background_opacity: $num" ~/.config/alacritty/alacritty.yml 
touch ~/.config/alacritty/alacritty.yml
