#! /bin/bash

# The Simple X Hotkey Daemon is the program used by LARBS to map most of the
# dwm-independent commands.  This file is pretty readable, so I'll let you read
# it.

# The keys NOT bound here by sxhkd, but by dwm or i3 are:
# The t thru p keys on the top row
# The f thru ; keys on the home row
# The b key on the bottom row (hides the bar in either case)

# Basic binds

#Texpander:
hyper + t
    /home/steve/scripts/texpander.sh &
    
# Emacs:
hyper + e
	bspc desktop --focus ^2 && emacs ~/.t.org

hyper + KP_Add
 	bopp

hyper + KP_Subtract
 	bopm

# Chord example:
super + a: {a,x}
    {bopp,bopm}

#Firefox:
hyper+w
	sidebarh
alt+f
	sidebarh

super + v
   rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' && xdotool key ctrl+v

